### ISSUE TITLE
Icons displaying too large.

### ISSUE THREAD

**Issue by Partymann2000** [teamblueprint/main#1]
![image](https://github.com/teamblueprint/main/assets/53320411/2992ba2e-77aa-4323-89d7-7fafe5066912)

**Comment by prplwtf** [comment]
Your browser cache has not been reloaded yet. Please use one of the following keybinds to refresh your browser cache (while on your admin dashboard).

Windows: `CTRL + SHIFT + R` or `CTRL + F5`
Linux: `CTRL + SHIFT + R` or `CTRL + F5`
MacOS: `CMD + OPTION + R`

**Comment by prplwtf** [comment]
Your browser cache has not been reloaded yet. Please use one of the following keybinds to refresh your browser cache (while on your admin dashboard).

Windows: `CTRL + SHIFT + R` or `CTRL + F5`
Linux: `CTRL + SHIFT + R` or `CTRL + F5`
MacOS: `CMD + OPTION + R`

**Comment by BlueTree242** [comment]
this solution is not working for me

**Comment by prplwtf** [comment]
@BlueTree242 You'll have to find a different way to refresh your webpage cache.

**Comment by BlueTree242** [comment]
I tried using Network tab and disable cache then reload which works for me when i am working on my own sites

**Comment by BlueTree242** [comment]
Could it be Cloudflare? What's the file that's cached?

**Comment by prplwtf** [comment]
Possible, yeah. The path to the css file is `domain.ext/assets/extensions/blueprint/blueprint.style.css`.

**Comment by prplwtf** [comment]
@BlueTree242 Alright, glad you fixed it.
