### ISSUE TITLE
Script requires ZIP, while readme doesn't say so

### ISSUE THREAD

**Issue by Codixer** [teamblueprint/main#13]
![image](https://github.com/teamblueprint/main/assets/25939526/a1f15d07-8d6c-4cb8-95dc-716756f02e3a)
![image](https://github.com/teamblueprint/main/assets/25939526/6134d67f-9baf-47c8-8fd2-b7a9f963c7e5)

While I understand the common sense part, there are people who won't know that they just run `sudo apt install zip` xD

**Comment by prplwtf** [comment]
You are currently looking at the README shipped with an earlier version of Blueprint. It's already correct on the developer builds and GitHub repo README.

**Comment by Ahwxorg** [comment]
Adding onto this quickly: people should just know how to correct this themselves if they're using Blueprint.

**Comment by Codixer** [comment]
> You are currently looking at the README shipped with an earlier version of Blueprint. It's already correct on the developer builds and GitHub repo README.
@prplwtf 

Ahhhhhh, fair. The release branch was for some reason still standard onto it.

> Adding onto this quickly: people should just know how to correct this themselves if they're using Blueprint.
@Ahwxorg 
Trust me, there will always be people stupid enough to say "Uhhh, how to I install zip?"

**Comment by Ahwxorg** [comment]
> > Adding onto this quickly: people should just know how to correct this themselves if they're using Blueprint.

> Trust me, there will always be people stupid enough to say "Uhhh, how to I install zip?"

Then they shouldn't install Blueprint :)
