### ISSUE TITLE
Installing Blueprint on Docker (on Unraid) discussion.

### ISSUE THREAD

**Issue by someone12421** [teamblueprint/main#14]
is there any way to install this on unraid?

**Comment by Ahwxorg** [comment]
How did you install Pterodactyl in Unraid?

**Comment by prplwtf** [comment]
Casually making this a discussion instead of a support question, because I feel like it might not have a simple answer.

**Comment by Ahwxorg** [comment]
@someone12421 pinging because we can't do anything but wait for your reply.

**Comment by someone12421** [comment]
I installed pterodactyl using docker

**Comment by Ahwxorg** [comment]
Elaborate?

**Comment by prplwtf** [comment]
While using Blueprint on Docker is definitely possible, you'd have to alter some of the functions in Blueprint's code and be able to tackle unknown problems.

Moving on, Blueprint on docker isn't officially supported at the moment.

**Comment by Ahwxorg** [comment]
I don't know if Unraid supports VMs, but you could try creating a Debian 12 VM and installing Pterodactyl onto that. Blueprint definitely supports Debian.

**Comment by prplwtf** [comment]
@someone12421 I will mark this issue as completed in a couple days due to inactivity.

**Comment by someone12421** [comment]
Ok
