### ISSUE TITLE
Replace admin cache refresh overlay with a notification/banner.

### ISSUE THREAD

**Issue by prplwtf** [teamblueprint/main#16]

**Comment by prplwtf** [comment]
![Image](https://github.com/teamblueprint/main/assets/103201875/b8f27457-ce4c-4b0f-b851-efe93af85851)

This is the current progress of the updated admin cache refresh reminder. I do think it could be improved, which is why I turned this into an issue.

**Comment by Ahwxorg** [comment]
Might be nice to use something like Nebula's shortcut showcase.

**Comment by prplwtf** [comment]
Maybe, but I might just keep this version of it for now.
