### ISSUE TITLE
How can I uninstall blueprint 

### ISSUE THREAD

**Issue by DawgTwist** [teamblueprint/main#7]
I am having a problem with it I just need a answer

**Comment by DawgTwist** [comment]
s

**Comment by prplwtf** [comment]
To uninstall Blueprint properly, you will need to do the following:
- Remove all files that are modified by Blueprint. By skipping this step, your panel will use up more storage than needed.
- Update your panel by following [the Pterodactyl documentation](https://pterodactyl.io/panel/1.0/updating.html).
